<a href="https://colab.research.google.com/github/lecacung-ai/TH_DeepLearning/blob/main/Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a=np.array([1,9,15,39])
print(a)

[ 1  9 15 39]


In [5]:
c=np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)
d=c.reshape(3,2)
print('reshape: (3,2) \n',d)
e=c.flatten()
print('flatten: \n',e)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64
reshape: (3,2) 
 [[1 2]
 [3 4]
 [5 6]]
flatten: 
 [1 2 3 4 5 6]


In [6]:
f=np.array([1.,2.,3.])
g=np.array([4.,5.,6.])
h_stack = np.hstack((f,g))
v_stack = np.vstack((f,g))
print('h_stack: \n',h_stack)
print('v_stack: \n',v_stack)

h_stack: 
 [1. 2. 3. 4. 5. 6.]
v_stack: 
 [[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
#Sinh mảng ngẫu nhiên với mảng có kích thước "Size"
a=np.random.randint(100,size = (5,))
print(a)
#Sinh mảng ngẫu nhiêu trong [0,1]
b = np.random.rand(5)
print(b)
#Sinh mảng ngẫu nhiên từ các giá trị cho trước kích thước "Size"
c = np.random.choice([9,3,5,1,2,4,6,7,8,0],size = (5,2))
print(c)

[27 97 10 21  8]
[0.07281534 0.81244838 0.77109804 0.32514678 0.10719537]
[[7 3]
 [2 9]
 [5 5]
 [6 3]
 [3 3]]


In [16]:
#Thay đổi giá trị ma trận với asarray
a= np.matrix(np.ones((5,5)))
print(a)
np.array(a)[2]=2
print('Ma trận sau khi đổi\n',a)
np.asarray(a)[2]=2
print('Ma trận sau khi đổi\n',a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Ma trận sau khi đổi
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Ma trận sau khi đổi
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
#Sinh dãy số theo khoảng [x,y] với mỗi bước tăng n giá trị arange(x,y,n)
a=np.arange(2,11,2)
print(a)

[ 2  4  6  8 10]


In [22]:
#lấy index
a=np.array([(1,2,3),(4,5,6)])
print(a)
print(a[:1,2]) #Lấy 1 dòng của cột 2
print(a[:2,:2]) #lấy 2 dòng và 2 cột
print(a[:,0]) #lấy tất cả các dòng của cột 0

[[1 2 3]
 [4 5 6]]
[3]
[[1 2]
 [4 5]]
[1 4]
2


In [ ]:
import pandas as pd
a=pd.Series([1.,2.,3.])
