<a href="https://colab.research.google.com/github/lecacung-ai/TH_DeepLearning/blob/main/Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#tạo mảng 1 chiều
import numpy as np
a=np.array([1,9,15,39])
print(a)

[ 1  9 15 39]


In [5]:
#mảng 2 chiều
c=np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)
#đổi kích thước mảng
d=c.reshape(3,2)
print('reshape: (3,2) \n',d)
#chuyển mảng thành dãy
e=c.flatten()
print('flatten: \n',e)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64
reshape: (3,2) 
 [[1 2]
 [3 4]
 [5 6]]
flatten: 
 [1 2 3 4 5 6]


In [6]:
#ghép 2 mảng theo chiều ngang
f=np.array([1.,2.,3.])
#ghép 2 mảng theo chiều dọc
g=np.array([4.,5.,6.])
h_stack = np.hstack((f,g))
v_stack = np.vstack((f,g))
print('h_stack: \n',h_stack)
print('v_stack: \n',v_stack)

h_stack: 
 [1. 2. 3. 4. 5. 6.]
v_stack: 
 [[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
#Sinh mảng ngẫu nhiên với mảng có kích thước "Size"
a=np.random.randint(100,size = (5,))
print(a)
#Sinh mảng ngẫu nhiêu trong [0,1]
b = np.random.rand(5)
print(b)
#Sinh mảng ngẫu nhiên từ các giá trị cho trước kích thước "Size"
c = np.random.choice([9,3,5,1,2,4,6,7,8,0],size = (5,2))
print(c)

[27 97 10 21  8]
[0.07281534 0.81244838 0.77109804 0.32514678 0.10719537]
[[7 3]
 [2 9]
 [5 5]
 [6 3]
 [3 3]]


In [16]:
#Thay đổi giá trị ma trận với asarray
a= np.matrix(np.ones((5,5)))
print(a)
np.array(a)[2]=2
print('Ma trận sau khi đổi\n',a)
np.asarray(a)[2]=2
print('Ma trận sau khi đổi\n',a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Ma trận sau khi đổi
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Ma trận sau khi đổi
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
#Sinh dãy số theo khoảng [x,y] với mỗi bước tăng n giá trị arange(x,y,n)
a=np.arange(2,11,2)
print(a)

[ 2  4  6  8 10]


In [25]:
#lấy index
a=np.array([(1,2,3),(4,5,6)])
print(a)
print(a[:1,2]) #Lấy 1 dòng của cột 2
print(a[:2,:2]) #lấy 2 dòng và 2 cột
print(a[:,0]) #lấy tất cả các dòng của cột 0

[[1 2 3]
 [4 5 6]]
[3]
[[1 2]
 [4 5]]
[1 4]


In [47]:
#pandas
import pandas as pd
#tạo pandas series
a = pd.Series([1.,2.,3.])
print(a)
print('First value: ',a[0])
b = pd.Series([1.,2.,3.],index = ['a','b','c'])
print(b)
print('First value: ',b['a'])

0    1.0
1    2.0
2    3.0
dtype: float64
First value:  1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value:  1.0


In [49]:
#tạo DataFrame
dic = {'Name':['John','Smith'],'Age':[30,40]}
df = pd.DataFrame(dic)
print(df)

    Name  Age
0   John   30
1  Smith   40


In [50]:
# Nối 2 DataFrame
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])

df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])

df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)

# Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicate values in DataFrame\n', df_concat.drop_duplicates('Name'))

# Sắp xếp theo cột
print('Sort values in DataFrame\n', df_concat.sort_values('Age'))

# Đổi tên cột
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [45]:
#Bài 1,2 lab 1
a = np.random.choice(np.arange(0,21),size = (3,3))
print(a)
print('Tất cả các phần tử trong mảng khác 0: ',np.all(a != 0))
print('Có ít nhất 1 phần tử trong mảng bằng 0: ',np.any(a == 0))

[[ 4 14  5]
 [ 9 12  0]
 [12  9 18]]
Tất cả các phần tử trong mảng khác 0:  False
Có 1 phần tử trong mảng bằng 0:  True
